MVC/Controllers/GuiderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC.Models;

namespace MVC.Controllers
{
    public class GuiderController : Controller
    {
        private DataBaseContext db = new DataBaseContext();

        public ActionResult ResetPassWord(int? id)
        {
            var guider = db.Guider.Find(id);
            var phone = guider.Phone as string;
            var new_password = "";
            for (int i = phone.Length - 3; i < phone.Length; i++)
            {
                new_password += phone[i];
            }
            guider.Password = new_password;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Guider
        public ActionResult Index()
        {
            return View(db.Guider.ToList());
        }

        // GET: Guider/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guider guider = db.Guider.Find(id);
            if (guider == null)
            {
                return HttpNotFound();
            }
            return View(guider);
        }

        // GET: Guider/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Guider/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Number,Password,Name,Phone")] Guider guider)
        {
            if (ModelState.IsValid)
            {
                db.Guider.Add(guider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(guider);
        }

        // GET: Guider/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guider guider = db.Guider.Find(id);
            if (guider == null)
            {
                return HttpNotFound();
            }
            return View(guider);
        }

        // POST: Guider/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Number,Password,Name,Phone")] Guider guider)
        {
            if (ModelState.IsValid)
            {
                db.Entry(guider).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(guider);
        }

        // GET: Guider/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guider guider = db.Guider.Find(id);
            if (guider == null)
            {
                return HttpNotFound();
            }
            return View(guider);
        }

        // POST: Guider/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Guider guider = db.Guider.Find(id);
            var guider_Schedules = db.Schedule.Where(x=> x.guider == guider.Number);
            foreach (var item in guider_Schedules)
            {
                if(item.title == "請假")
                {
                    db.Schedule.Remove(item);
                }
                else
                {
                    item.guider = "";
                }
            }
            db.Guider.Remove(guider);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC.Models;
using Newtonsoft.Json;

namespace MVC.Controllers
{
    public class MainController : Controller
    {
        private DataBaseContext db = new DataBaseContext();
        private Repository repository = new Repository();
        // GET: Main
        public ActionResult Index(string id = null)
        {
            MainViewModel model = new MainViewModel();
            model.Guiders = db.Guider.ToList();
            model.Schedulable_Event = db.Schedule.Where(x => (x.guider == null) || (x.guider == "")).ToList();
            if (id != null)
            {
                string Name = "";
                var guider = db.Guider.Where(x => x.Number == id).Single();
                Name = guider.Name;
                ViewBag.Name = Name;
            }
            return View(model);
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection post)
        {
            string account = post["account"];
            string password = post["password"];
            var result = db.UserData.Where(x => x.account == account && x.password == password).ToList();

            //驗證密碼
            if (result.Capacity != 0)
            {
                //若登入成功，用Session紀錄帳號，並在需要登入驗證的View加上檢查Seesion的紀錄
                //Ex.Views/Main/Index
                Session["account"] = account;

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Msg = "登入失敗...";
                return View();
            }
        }
        public ActionResult Logout()
        {
            Session.RemoveAll();
            return Redirect(Url.Content("~/Main/Login"));
        }

        public ActionResult Register()
        {
            FormDataModel model = new FormDataModel();
            model.Cities = db.City.ToList();

            return View(model);
        }

        [HttpPost]
        public ActionResult Register(FormUserData data)
        {
            FormDataModel model = new FormDataModel();
            if (string.IsNullOrWhiteSpace(data.password1) || data.password1 != data.password2)
            {
                model.Cities = db.City.ToList();
                if (!string.IsNullOrWhiteSpace(data.city))
                    model.villages = db.Village.Where(x => x.CityId == data.city).ToList();
                model.userData = data;
                ViewBag.Msg = "密碼輸入錯誤";
                return View(model);
            }
            else
            {
                try
                {
                    UserData user = new UserData();
                    user.account = data.account;
                    user.password = data.password1;
                    user.city = data.city;
                    user.village = data.village;
                    user.address = data.address;
                    db.UserData.Add(user);
                    db.SaveChanges();
                    Response.Redirect("~/Main/Login");
                    return new EmptyResult();
                }
                catch (Exception e)
                {
                    ViewBag.Msg = e;
                    return View(model);
                }
            }
        }

        public ActionResult _ModalView(int? id)
        {
            MainViewModel model = new MainViewModel();

            var Event = db.Schedule.Find(id);//欲分派行程
            var Guiders = db.Guider.ToList();
            var Guiders_list = new List<string> { };
            foreach (var item in Guiders)
            {
                Guiders_list.Add(item.Number);
            }
            var Schedule_list = db.Schedule.ToList();
            foreach (var item in Schedule_list)
            {
                if (item.id != Event.id)
                {
                    DateTime start = item.start;
                    DateTime end = item.end;

                    //Compare(x,y) return   1:x>y   ,0:x=y,    -1:x<y
                    //如果你開始時間比別人的晚或同天，且你的結束時間比別人的早 或 你結束時間比別人的開始時間晚又比別人的結束時間早
                    if (!((DateTime.Compare(Event.start, start) < 0 && DateTime.Compare(Event.end, start) < 0)
                        || (DateTime.Compare(Event.start, end) > 0 && DateTime.Compare(Event.end, end) > 0)))
                    {
                        Guiders_list.Remove(item.guider);
                    }
                }
            }
            var result = new List<Guider>();
            foreach (var item in Guiders_list)
            {
                var temp = db.Guider.Where(x => x.Number == item).Single();
                result.Add(temp);//適合之導遊清單
            }
            model.Guiders = result;
            model.Scheules = new List<Schedule>();
            model.Scheules.Add(Event);
            return View(model);
        }

        public ActionResult _Event_Modal(int? id)
        {
            var result = db.Schedule.Find(id);
            return View(result);
        }

        public ActionResult Assign(int id, string guider = null)
        {
            try
            {
                var schedule = db.Schedule.Find(id);
                if (schedule != null)
                {
                    schedule.guider = guider;
                }
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                // Info 
                ViewBag.Msg = ex.ToString();
            }
            return RedirectToAction("Index");
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------//
        //------------------------------------------------------------Function---------------------------------------------------------------------//
        //-----------------------------------------------------------------------------------------------------------------------------------------//

        public bool AddUserData(FormUserData data)
        {
            try
            {
                UserData user = new UserData();
                user.account = data.account;
                user.password = data.password1;
                user.city = data.city;
                user.village = data.village;
                user.address = data.address;
                db.UserData.Add(user);
                db.SaveChanges();
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        //檢測日期有無衝突
        public bool Check_Confilct(int id, string guider)
        {
            Schedule com_event = db.Schedule.Find(id);
            TimeSpan Com_Duration = com_event.end - com_event.start;
            List<Schedule> list = db.Schedule.Where(x => x.guider == guider).ToList();
            bool Is_Conflict = false;
            for (int i = 0; i < list.Count; i++)
            {
                DateTime start = list[i].start;
                DateTime end = list[i].end;

                //如果你開始時間比別人的晚或同天，且你的結束時間比別人的早 或 你結束時間比別人的開始時間晚又比別人的結束時間早
                if (!((DateTime.Compare(com_event.start, start) < 0 && DateTime.Compare(com_event.end, start) < 0)
                    || (DateTime.Compare(com_event.start, end) > 0 && DateTime.Compare(com_event.end, end) > 0)))
                {
                    if (id != list[i].id)
                    {
                        Is_Conflict = true;
                        break;
                    }
                }
            }
            return Is_Conflict;
        }

        public FileResult GetReport(int? id)
        {
            var result = db.Schedule.Find(id);
            byte[] FileBytes = System.IO.File.ReadAllBytes(result.filepath);
            return File(FileBytes, "application/pdf");
        }

        public ActionResult Cancel(int? id)
        {

            var schedule = db.Schedule.Find(id);
            try
            {
                if (schedule != null)
                {
                    schedule.guider = null;
                    db.SaveChanges();
                    ViewBag.Msg = "已取消分派行程!!";
                }
            }
            catch (Exception ex)
            {
                // Info 
                ViewBag.Msg = ex.Message.ToString();
            }

            return RedirectToAction("Index",new {id= schedule.guider});
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------//
        //------------------------------------------------------------Ajax Call---------------------------------------------------------------------//
        //-----------------------------------------------------------------------------------------------------------------------------------------//

        [HttpPost]
        public JsonResult FindBestGuiders(int? id)
        {
            var Event = db.Schedule.Find(id);//欲分派行程
            var Guiders = db.Guider.ToList();
            var Guiders_list = new List<string> { } ;
            foreach (var item in Guiders)
            {
                Guiders_list.Add(item.Number);
            }
            var Schedule_list = db.Schedule.ToList();
            foreach (var item in Schedule_list)
            {
                if(item.id != Event.id)
                {
                    DateTime start = item.start;
                    DateTime end = item.end;

                    //如果你開始時間比別人的晚或同天，且你的結束時間比別人的早 或 你結束時間比別人的開始時間晚又比別人的結束時間早
                    if ((DateTime.Compare(Event.start, start) >= 0 && DateTime.Compare(Event.start, end) < 0)
                        || (DateTime.Compare(Event.end, start) >= 0 && DateTime.Compare(Event.end, end) < 0))
                    {

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 主管端介面</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fullcalendar")
    @Styles.Render("~/Content/qtip")
    @Styles.Render("~/Content/gijgo")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        @Html.ActionLink("主管端介面", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">@Html.ActionLink("首頁", "Index", "Main", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("使用者", "Index", "UserData", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("行程", "Index", "Schedule", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("導遊", "Index", "Guider", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("請假申請", "Index", "Leaves", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("登出", "Logout", "Main", new { area = "" }, new { @class = "nav-link" })</li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid p-lg-5 py-md-4">
        @RenderBody()
    </div>
    <hr />
    <footer>
        <center>&copy; @DateTime.Now.Year - 導遊派遣系統</center>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryUI")


    <!-- Include moment-->
    @Scripts.Render("~/bundles/moment")

    <!-- qTip -->
    @Scripts.Render("~/bundles/qtip")

    <!-- Full Calendar -->
    @Scripts.Render("~/bundles/fullcalendar")
    @Scripts.Render("~/bundles/Calendar-locale")
    <!-- Date Picker -->
    @Scripts.Render("~/bundles/DatePicker")
    @*@Scripts.Render("~/bundles/gijgo")*@
    @RenderSection("scripts", required: false)
</body>
</html>

MVC/Views/Shared/_PartialEvents.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 主管端介面</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fullcalendar")
    @Styles.Render("~/Content/qtip")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <div class="navbar-brand">主管端介面</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            </ul>
        </div>
    </nav>

    <div class="container-fluid p-lg-5 py-md-4">
        @RenderBody()
    </div>
    <hr />
    <footer>
        <center>&copy; @DateTime.Now.Year - 導遊派遣系統</center>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryUI")


    <!-- Include moment-->
    @Scripts.Render("~/bundles/moment")

    <!-- qTip -->
    @Scripts.Render("~/bundles/qtip")

    <!-- Full Calendar -->
    @Scripts.Render("~/bundles/fullcalendar")
    @*@Scripts.Render("~/bundles/Script-calendar")*@
    @Scripts.Render("~/bundles/Calendar-locale")
    @Scripts.Render("~/bundles/DatePicker")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC/Views/Shared/_StyleLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fullcalendar")
    @Scripts.Render("~/bundles/modernizr")
    <!-- qTip -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/qtip2/3.0.3/jquery.qtip.min.css" />

    <!-- Full Calendar -->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <center>
                <p><strong>Copyright © @DateTime.Now.Year - <a href="http://www.asmak9.com/">Asma's Blog</a>.</strong> All rights reserved.</p>
            </center>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <!-- Include moment-->
    @Scripts.Render("~/bundles/moment")

    <!-- qTip -->
    @Scripts.Render("~/bundles/qtip")

    <!-- Full Calendar -->
    @Scripts.Render("~/bundles/fullcalendar")
    @Scripts.Render("~/bundles/Script-calendar")

    @RenderSection("scripts", required: false)
</body>
</html>  